const chapters=window.FULL_CHAPTERS||[
{no:'03',title:'代数式',goal:'从数量关系到字母表达，建立代数语言。',units:[
['3.1','用字母表示数','理解字母可以表示数、数量关系和变化规律。','n盒彩笔，每盒6支，共有多少支？',['6n','n+6','6÷n'],0,'每盒数量×盒数，所以是6n。','数量关系先确定运算，再用字母代替变化的量。',['物理：路程模型','s=vt也是用字母表达数量关系。','高中会把变量间关系发展为函数：一个量变化，另一个量随之变化。']],
['3.2','代数式','识别单独一个数、一个字母及运算组合都是代数式。','下列哪一个是代数式？',['3x+2','3x+2=8','请计算3x'],0,'代数式不含等号，3x+2是代数式。','代数式表达数量或数量关系，不负责断言两个量相等。',['英语：数学表达','3x+2可读作 three x plus two。','数学语言跨语言高度稳定，符号是全球通用的表达系统。']],
['3.3','代数式的值','把给定字母值代入，并严格按运算顺序计算。','当a=−2时，3a²−1等于？',['11','−13','5'],0,'先算a²=4，再算3×4−1=11。','代入时负数必须加括号，乘方优先于乘法和减法。',['编程：变量赋值','程序中的变量也会被赋值后参与表达式计算。','a=-2后，表达式求值仍遵循运算优先级；括号能避免符号歧义。']],
['3.4','单项式','掌握单项式的系数、次数以及π作为数字因数。','−3πx²y的次数是多少？',['3','2','−3'],0,'x的指数2与y的指数1相加，次数为3。','单项式次数是所有字母指数之和，系数不计入次数。',['物理：量纲','物理公式也关注各个量以怎样的次数组合。','面积与长度平方相关，体积与长度立方相关，这是次数的现实含义。']],
['3.5','多项式','识别项、常数项、次数并按次数降幂排列。','多项式2x³−x+5的次数是？',['3','2','5'],0,'最高次数项2x³的次数为3。','多项式次数等于其中次数最高的项的次数。',['高中预览：多项式函数','多项式将继续发展为函数、因式分解和方程。','高中会研究多项式图像、零点与因式之间的关系。']]]},
{no:'04',title:'整式的加减',goal:'从同类结构到去括号与化简，掌握符号变形。',units:[
['4.1','同类项','识别所含字母相同且相同字母指数也相同的项。','下列哪一项与3x²y是同类项？',['−5x²y','3xy²','3x²'],0,'字母与对应指数完全相同，系数可以不同。','判断同类项只看字母部分，不看系数和排列顺序。',['化学：同类粒子','化学方程式配平只能合并同种粒子。','像代数合并同类项一样，物质种类不同不能直接合并数量。']],
['4.2','合并同类项','系数相加减，字母部分保持不变。','5a−2a+3等于？',['3a+3','3a','6a'],0,'5a−2a=3a，常数3不能与a项合并。','合并同类项是分配律的逆用，字母部分不改变。',['计算机：符号计算','计算机代数系统会先识别表达式结构再化简。','它不是看起来像就合并，而是匹配变量和指数结构。']],
['4.3','去括号','根据括号前符号决定括号内各项是否变号。','−(2x−3)等于？',['−2x+3','−2x−3','2x+3'],0,'括号前是负号，括号内每一项都变号。','负号相当于乘以−1，必须分配给括号内每一项。',['几何：整体变换','把整个图形镜像，相当于所有方向同时改变。','去括号变号不是局部操作，而是−1作用于括号内的整体。']],
['4.4','整式加减','先去括号，再合并同类项，并保持书写规范。','(3x+2)−(x−4)化简为？',['2x+6','2x−2','4x+6'],0,'去括号得3x+2−x+4，再合并为2x+6。','整式加减的核心流程是去括号、找同类项、合并。',['财务：净变化','收入与支出模型本质上也是带符号项目的合并。','不同类别先分类，同类别再汇总，这与合并同类项一致。']],
['4.5','数字规律探索','用整式表达连续整数、奇偶数与图形增长规律。','三个连续整数，中间一个为n，它们的和是？',['3n','3n+3','n³'],0,'三个数为n−1、n、n+1，和为3n。','先用字母统一描述结构，再化简揭示不变量。',['高中预览：数列','图形增长规律会发展为数列与递推关系。','高中会研究等差数列、等比数列以及第n项和前n项和。']]]},
{no:'05',title:'一元一次方程',goal:'把实际问题翻译成方程，并用等式性质求解。',units:[
['5.1','从算式到方程','理解未知数、方程和解，建立等量关系。','“某数的3倍减2等于10”应列为？',['3x−2=10','3x−2','x−2=30'],0,'题目包含未知数和等量关系，因此是3x−2=10。','方程必须含未知数和等号，等号两边表示同一个量。',['物理：平衡状态','很多物理定律用方程表达平衡或守恒。','受力平衡、能量守恒都在寻找两个表达式相等的条件。']],
['5.2','等式的性质','理解等式两边同时进行相同运算仍保持相等。','若a=b，下列一定成立的是？',['a+5=b+5','a+5=b−5','5a=b'],0,'等式两边同时加5，等式仍成立。','天平两侧必须进行完全相同且合法的操作。',['实验：天平模型','方程变形可以看作保持天平平衡。','两边同时增减同一质量，或同时按相同比例变化，平衡不被破坏。']],
['5.3','解一元一次方程','掌握去分母、去括号、移项、合并和系数化1。','解3x−5=10，x等于？',['5','15','5/3'],0,'移项得3x=15，再把系数化为1，x=5。','移项本质是等式两边同时加减同一个式子。',['历史：方程术','中国《九章算术》很早就系统处理方程问题。','古代筹算中的“正负术”也是现代代数符号思想的重要源头。']],
['5.4','实际问题建模','经历设未知数、列方程、求解、检验与作答。','一件商品打8折后80元，原价x元，方程是？',['0.8x=80','x−8=80','8x=80'],0,'打8折表示现价是原价的80%。','先找题目中的等量关系，再决定未知数与单位。',['经济：折扣与税率','折扣、利率和增长率都能转化为方程模型。','高中会进一步研究分段计费、复利和优化问题。']],
['5.5','工程与行程问题','用总量、效率、时间以及路程、速度、时间建模。','甲每小时做6件，乙每小时做4件，合作x小时做50件，方程是？',['(6+4)x=50','6x+4=50','10+x=50'],0,'合作效率为10件/小时，总量=效率×时间。','先确定统一总量，再把各部分贡献相加。',['物理：运动模型','路程、速度与时间是初中物理的重要连接点。','相遇与追及问题可画位置—时间图，高中会进一步研究速度变化。']]]},
{no:'06',title:'几何图形初步',goal:'从空间物体到点线面体，建立几何语言与度量意识。',units:[
['6.1','立体图形与平面图形','识别柱体、锥体、球体及展开图、三视图。','圆柱从正面看到的平面图形通常是？',['长方形','圆','三角形'],0,'直立圆柱的正视图通常是长方形。','同一立体从不同方向观察，会得到不同平面图形。',['工程：三视图','工程制图用主视图、俯视图和左视图表达立体。','这也是建筑、机械设计和3D建模的重要基础。']],
['6.2','点、线、面、体','理解几何图形由基本元素构成及运动关系。','线动成面，面动成什么？',['体','点','线'],0,'面沿不在该面内的方向运动可以形成体。','点动成线、线动成面、面动成体体现维度扩展。',['高中预览：维度','点、线、面、体分别对应0、1、2、3维。','坐标系让维度可以用有序数组表达，高中将学习空间向量。']],
['6.3','直线、射线、线段','掌握表示方法、基本事实和线段大小比较。','经过两点可以确定多少条直线？',['一条','两条','无数条'],0,'两点确定一条直线。','直线由两点唯一确定；线段有长度，射线与直线可无限延伸。',['地图：最短路线','两点之间线段最短是路径规划的基础模型。','真实道路受障碍影响，高级算法会在图网络中寻找最短路径。']],
['6.4','角与角的度量','理解角、度分秒换算及角的比较。','1°等于多少分？',['60′','100′','360′'],0,'角度采用六十进制，1°=60′。','角的大小取决于两边张开的程度，与边画多长无关。',['地理：经纬度','地理坐标也使用度、分、秒表示位置。','经纬度把球面位置转化为角度，导航系统再换算为空间坐标。']],
['6.5','余角、补角与方位角','掌握互余、互补关系并解决方向问题。','一个角为35°，它的补角是？',['145°','55°','325°'],0,'两个角和为180°时互为补角，180°−35°=145°。','互余看和是否为90°，互补看和是否为180°。',['物理：反射角','光的反射、力的分解都需要准确处理方向与角度。','高中物理会用三角函数把一个方向上的量分解到两个互相垂直的方向。']]]}
];
const $=id=>document.getElementById(id),params=new URLSearchParams(location.search);let ci=Math.max(0,Math.min(3,(+params.get('chapter')||3)-3)),ui=0,step=0,wrong=0;const done=JSON.parse(localStorage.getItem('yuanlai_3_6_done')||'{}');
function chapter(){return chapters[ci]}function unit(){return chapter().units[ui]}function render(){const c=chapter(),u=unit();$('topTitle').textContent=`第${['三','四','五','六'][ci]}章 ${c.title}`;$('chapterNo').textContent=`CHAPTER ${c.no}`;$('chapterTitle').textContent=c.title;$('chapterGoal').textContent=c.goal;$('chapterSwitch').innerHTML=`<button data-link="chapter1.html">01</button><button data-link="course.html">02</button>`+chapters.map((x,i)=>`<button class="${i===ci?'active':''}" data-c="${i}">${x.no}</button>`).join('');document.querySelectorAll('[data-link]').forEach(b=>b.onclick=()=>location.href=b.dataset.link);$('units').innerHTML=c.units.map((x,i)=>`<button class="${i===ui?'active':''} ${done[`${ci}-${i}`]?'done':''}" data-u="${i}"><i>${done[`${ci}-${i}`]?'✓':i+1}</i><span>${x[1]}<small>${x[0]}</small></span></button>`).join('');document.querySelectorAll('[data-c]').forEach(b=>b.onclick=()=>{ci=+b.dataset.c;ui=0;step=0;history.replaceState(null,'',`?chapter=${ci+3}`);render()});document.querySelectorAll('[data-u]').forEach(b=>b.onclick=()=>{ui=+b.dataset.u;step=0;render()});$('unitCode').textContent=`MISSION ${u[0]}`;$('unitTitle').textContent=u[1];$('unitGoal').textContent=u[2];$('worldTitle').textContent=u[1]+'概念实验';$('question').textContent=u[3];$('questionCopy').textContent=step?'请说明你使用的规则，再迁移到新的表达。':'先观察动态模型，再独立作出判断。';$('ccSpeech').textContent=step?'不要只记答案，把判断依据说出来。':'先找关系和条件，再动手。';$('rule').textContent=u[7];$('portalTitle').textContent=u[8][0];$('portalCopy').textContent=u[8][1];$('portalDetail').textContent=u[8][2];$('portalDetail').classList.add('hidden');$('answers').innerHTML=u[4].map((x,i)=>`<button data-a="${i}">${x}</button>`).join('');$('feedback').classList.add('hidden');$('next').classList.add('hidden');$('world').classList.remove('pulse');$('visual').innerHTML=visualFor(u);document.querySelectorAll('[data-a]').forEach(b=>b.onclick=()=>answer(+b.dataset.a,b));$('practiceQ').textContent=`为什么“${u[4][u[5]]}”成立？`;$('practiceAnswers').innerHTML=[u[7],'因为它看起来最熟悉','只要记住这道题'].map((x,i)=>`<button data-p="${i}">${x}</button>`).join('');document.querySelectorAll('[data-p]').forEach(b=>b.onclick=()=>practice(+b.dataset.p,b));diagnose();progress()}
function geometryVisual(u){const code=u[0];if(code==='6.1.2')return `<div class="geo-demo net"><div class="net-grid">${'<i></i>'.repeat(6)}</div><b>展开 ⇄ 折叠</b><span>观察六个面如何组成正方体</span></div>`;if(code==='6.1.3')return `<div class="geo-demo views"><div class="solid"><i></i><i></i><i></i></div><div class="view-cards"><b>正视图</b><b>左视图</b><b>俯视图</b></div></div>`;if(code.startsWith('6.2'))return `<div class="geo-demo segment"><i class="point a"></i><i class="point m"></i><i class="point b"></i><em></em><span class="la">A</span><span class="lm">M</span><span class="lb">B</span><b>${code==='6.2.4'?'AM = MB':'两点之间线段最短'}</b></div>`;if(code.startsWith('6.3'))return `<div class="geo-demo angle"><i class="ray fixed"></i><i class="ray moving"></i><i class="vertex"></i><em></em><b>${code==='6.3.5'?'角平分线':'角的开合'}</b><span>观察角度随射线转动</span></div>`;return `<div class="geo-demo solid-spin"><div class="cube"><i></i><i></i><i></i></div><b>旋转观察立体</b><span>从空间图形到平面视图</span></div>`}
function visualFor(u){const scenes={03:"linear-gradient(90deg,#101c3bf0,#101c3b99),url('./zero-world-v1.png') center/cover",04:"linear-gradient(90deg,#101c3be9,#101c3b91),url('./zero-bridge-clean-v4.png') center/cover",05:"linear-gradient(90deg,#101c3bed,#101c3b9c),url('./zero-observatory-diagonal-v2.webp') center/cover",06:"linear-gradient(90deg,#071426ed,#071426a8),url('./zero-observatory-premium-v1.webp') center/cover"};$('world').style.background=scenes[chapter().no];if(chapter().no==='06'&&window.GeometryLab)return window.GeometryLab.render(u);const bits=u[3].replace(/[？?]/g,'').split(/[，,；;]/).slice(0,3);return bits.map((x,i)=>`${i?'<b class="operator">→</b>':''}<div class="token">${x.length>9?x.slice(0,9):x}</div>`).join('')}
function answer(i,b){if(i!==unit()[5]){b.classList.add('wrong');wrong++;$('ccSpeech').textContent='这次错误已经记录。回到母规则，检查条件是否完整。';diagnose();return}b.classList.add('correct');document.querySelectorAll('[data-a]').forEach(x=>x.disabled=true);$('feedback').textContent=unit()[6];$('feedback').classList.remove('hidden');$('next').classList.remove('hidden');$('world').classList.add('pulse');$('mastery').textContent=wrong?'76%':'92%';step=1}
function practice(i,b){if(i){b.classList.add('wrong');wrong++;$('practiceFeedback').textContent='这只是答案印象，不是可以迁移的理由。请回到本课母规则。';$('practiceFeedback').classList.remove('hidden');diagnose();return}b.classList.add('correct');$('practiceFeedback').textContent='理由成立。现在回到探索区完成迁移，或进入下一课。';$('practiceFeedback').classList.remove('hidden');done[`${ci}-${ui}`]=1;localStorage.setItem('yuanlai_3_6_done',JSON.stringify(done));progress()}
function diagnose(){$('diagnosis').innerHTML=`<div class="diagnostic"><span>概念识别</span><b>${step?'已验证':'观察中'}</b></div><div class="diagnostic"><span>理由表达</span><b>${done[`${ci}-${ui}`]?'已通过':'待训练'}</b></div><div class="diagnostic"><span>错因记录</span><b>${wrong?wrong+'次':'暂无'}</b></div>`}
function progress(){const n=chapter().units.filter((_,i)=>done[`${ci}-${i}`]).length;$('progressText').textContent=`${n} / ${chapter().units.length}`;$('progressBar').style.width=`${n/chapter().units.length*100}%`;$('mastery').textContent=done[`${ci}-${ui}`]?'100%':step?(wrong?'76%':'92%'):'0%'}
$('next').onclick=()=>{if(ui<chapter().units.length-1){ui++;step=0;render()}else{done[`${ci}-${ui}`]=1;localStorage.setItem('yuanlai_3_6_done',JSON.stringify(done));if(ci<3){ci++;ui=0;step=0;history.replaceState(null,'',`?chapter=${ci+3}`);render()}}};document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-mode]').forEach(x=>x.classList.toggle('active',x===b));['explore','practice','repair'].forEach(x=>$(`${x}Panel`).classList.toggle('hidden',x!==b.dataset.mode))});$('portalBtn').onclick=()=>{const hidden=$('portalDetail').classList.toggle('hidden');$('portalBtn').textContent=hidden?'打开支线探索 →':'返回教材主线 ↑'};$('scan').onclick=()=>{$('repairTitle').textContent=wrong?'发现“条件遗漏”漏洞':'进行一次预防性修复';$('repairCopy').textContent=wrong?`你在本课出现${wrong}次错误。请重新说出母规则：“${unit()[7]}”`:`请不看答案复述：“${unit()[7]}”`;wrong=0;diagnose()};$('full').onclick=()=>document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen();render();
