const params=new URLSearchParams(location.search),focusKnowledge=params.get('focus')||'',book=window.YUANLAI_BOOKS.find(x=>x.id===params.get('book'))||window.YUANLAI_BOOKS[0];let unit=Math.max(0,Math.min(book.chapters.length-1,+params.get('unit')||0)),section=0,stage=0;document.documentElement.style.setProperty('--accent',book.color);const deep=book.id==='math7b'?(unit===0?window.MATH7B_CH7:window.MATH7B_REST?.[unit]):window.SUBJECT_DEEP?.[book.id]?.[unit]||null;if(deep)book.chapters[unit].sections=deep.sections;
const enrichment=book.id==='math7b'?window.MATH7B_ENRICHMENT?.[unit+7]:book.subject==='物理'?window.PHYSICS_ENRICHMENT?.find(x=>x.chapter===`${book.id==='phy8a'?'8A':'8B'}-${unit+1}`):book.subject==='英语'?window.ENGLISH_ENRICHMENT?.find(x=>x.book===(book.id==='eng7a'?'7A':'7B')&&x.unit===book.chapters[unit].title):null;
const verifiedLesson=()=>window.StudyMateVerifiedCourses?.get(book.id,unit,section)||null;
const enrichmentPoints=()=>enrichment?(enrichment.concepts||enrichment.points||[]):[];
const knowledgePoints=()=>{const verified=verifiedLesson();if(verified)return[verified.knowledge];if(!enrichment)return[];if(book.subject==='数学'){const groups=window.MATH7B_ENRICHMENT?.[unit+7]||[],g=groups[Math.min(section,groups.length-1)];return g?.concepts||[]}if(book.subject==='物理')return enrichment.points||[];if(book.subject==='英语')return [`Vocabulary · ${enrichment.vocab||0}词`,...(enrichment.pron||[]).map(x=>'Pronunciation · '+x),...(enrichment.grammar||[]).map(x=>'Grammar · '+x),...(enrichment.listening||[]).map(x=>'Listening · '+x),...(enrichment.speaking||[]).map(x=>'Speaking · '+x),'Reading · '+enrichment.reading,'Writing · '+enrichment.writing,'AI Conversation · '+enrichment.ai,'Project · '+enrichment.project,'Mastery Check'];return[]};
let knowledgeIndex=0,tutorLevel=0;
function currentKnowledge(){const list=knowledgePoints();if(focusKnowledge){const i=list.findIndex(x=>x===focusKnowledge||x.includes(focusKnowledge)||focusKnowledge.includes(x));if(i>=0)knowledgeIndex=i}return list[Math.min(knowledgeIndex,Math.max(0,list.length-1))]||book.chapters[unit].sections[section]}
function localCurriculumCode(){
 const s=book.chapters[unit].sections[section],m=s.match(/^(\d+\.\d+)/);
 if(book.id==='math7b'&&m)return 'M7B-'+m[1];
 if(book.id==='phy8a')return 'P8A-'+(unit+1)+'.'+(section+1);
 if(book.id==='phy8b')return 'P8B-'+(unit+7)+'.'+(section+1);
 if(book.id==='eng7a')return unit<3?'E7A-S'+(unit+1):'E7A-'+(unit-2);
 if(book.id==='eng7b')return 'E7B-'+(unit+1);
 return null;
}
function localHash(text){let h=2166136261;for(const ch of String(text||'')){h^=ch.charCodeAt(0);h=Math.imul(h,16777619)}return(h>>>0).toString(36)}
function learningContext(extra={}){
 const raw={book:book.id,uiBookId:book.id,subject:book.subject,chapter:book.chapters[unit].title,sectionTitle:book.chapters[unit].sections[section],knowledge:currentKnowledge(),...extra};
 if(window.StudyMateLearningIdentity)return window.StudyMateLearningIdentity.resolve(raw);
 const curriculumCode=localCurriculumCode(),same=String(raw.knowledge||'').trim()===String(raw.sectionTitle||'').trim();
 const mathParent=/^\d+\.\d+\s/.test(raw.sectionTitle||'')&&!/^\d+\.\d+\.\d+/.test(raw.sectionTitle||'');
 const root=same&&(book.id==='phy8a'||book.id==='phy8b'||(book.id==='math7b'&&mathParent));
 return curriculumCode?{...raw,curriculumCode,learningId:root?curriculumCode+'::root':curriculumCode+'::k:'+localHash(raw.knowledge),parentKnowledge:raw.sectionTitle}:raw;
}
function renderKnowledgeMap(){const list=knowledgePoints(),host=$('knowledgeMap');if(!host)return;host.innerHTML=list.length?list.map((x,i)=>`<button data-k="${i}" class="${i===knowledgeIndex?'active':''}"><i>${i+1}</i><span>${x}</span></button>`).join(''):'';host.querySelectorAll('[data-k]').forEach(b=>b.onclick=()=>{knowledgeIndex=+b.dataset.k;stage=0;tutorLevel=0;render()})}
const $=x=>document.getElementById(x),stageNames=['讲授','例1','例2','反例','例题','解释','迁移','小结'];
const evidenceStage=()=>{
 const common=['concept','concept','concept','concept','procedure','explanation','transfer','retention'];
 if(book.subject==='物理')return ['concept','experiment','evidence','evidence','procedure','explanation','transfer','mastery-check'][stage];
 if(book.subject==='英语'){const k=currentKnowledge();if(/^Speaking|^Writing|^AI Conversation/.test(k))return ['concept','speaking','speaking','concept','procedure','explanation','conversation','mastery-check'][stage];if(/^Listening/.test(k))return ['concept','procedure','procedure','concept','procedure','explanation','transfer','mastery-check'][stage];return ['concept','concept','procedure','concept','procedure','explanation','transfer','mastery-check'][stage]}
 return stage===7?'mastery-check':common[stage];
};
function lessonText(ch,s){const name=ch.sections[s],kp=currentKnowledge(),verified=verifiedLesson(),spec=window.StudyMateKnowledgeEngine?.get(book.subject,kp);if(verified)return verified.stages.map(x=>[x.title,x.copy]);if(spec&&knowledgePoints().length)return [['概念入口',spec.intro],['观察与例子',`先用一个具体例子理解“${kp}”，再改变条件观察什么保持不变。`],['独立判断',spec.q],['反例诊断',`常见错误：${spec.error}。改变关键条件，检查原结论为什么失效。`],['针对练习',spec.q],['解释母规则',spec.explain],[ch.cross.title,ch.cross.copy],['掌握检测',`不用提示，重新解释“${kp}”，完成一道变式并说明依据。`]];if(deep)return deep.lessons[s].stages;if(book.subject==='英语')return[
['先进入真实交流情境',`围绕 “${name}” 先理解说话目的，再学习词汇、语音和句型。`],['听辨与跟读',`观察人物、场景和语调变化；把关键词放进完整句子，而不是孤立背单词。`],['正例对话',`听一组自然对话，标出谁在说、为什么说、怎样回应。`],['反例诊断',`检查直译、时态、单复数或语调错误，说明为什么会让意思改变。`],['教材任务',`完成本节听说读写任务，并把答案放回原文或对话验证。`],['表达理由',`用自己的话复述规则，再生成一句没有照抄教材的新表达。`],[ch.cross.title,ch.cross.copy],['本节输出',`完成一段口头表达、一段短文和一份语音/语法自检。`]
];if(book.subject==='物理')return[
['从现象提出问题',`观察“${name}”中的现象，先区分看到的事实和自己的猜想。`],['操控变量看变化',`改变一个条件，保持其他条件不变，观察图像、读数或运动怎样变化。`],['正例实验',`按器材—步骤—数据—结论完整走一遍，结论必须由证据支持。`],['反例诊断',`检查是否同时改变多个变量、读数错误或把相关关系误当因果关系。`],['教材实验与例题',`回到教材任务，记录单位、有效数字、条件和计算过程。`],['解释规律',`用现象、模型和公式三种表示解释同一个规律。`],[ch.cross.title,ch.cross.copy],['本节模型',`整理概念、实验依据、公式适用条件与现实应用。`]
];return [
['从问题建立概念',`学习“${name}”时先看它解决什么问题，再给出定义和条件。`],['动态图形观察',`拖动点、线、图形或数据，观察变化量与不变量。`],['正例推理',`完整写出已知条件、判断依据和结论，不跳过关键一步。`],['反例诊断',`改变一个必要条件，观察原结论为什么不再成立。`],['教材例题',`按教材方法完成例题，并用图形、估算或代入进行检查。`],['解释母规则',`把本题答案还原成能解决一类问题的规则。`],[ch.cross.title,ch.cross.copy],['知识链小结',`用概念—表示—方法—易错点—应用五项完成本节总结。`]
]}
function geometryVisual(){const item=deep.lessons[section],bad=stage===3,angle=bad?72:50;const diagrams={intersect:`<svg viewBox="0 0 640 210" aria-label="两条相交直线动态图"><line x1="70" y1="105" x2="570" y2="105"/><line class="moving-line" x1="120" y1="185" x2="520" y2="25"/><circle cx="320" cy="105" r="5"/><text x="385" y="86">∠1 ${angle}°</text><text x="232" y="86">∠2 ${180-angle}°</text><text x="385" y="142">∠3 ${angle}°</text></svg>`,perpendicular:`<svg viewBox="0 0 640 210"><line x1="80" y1="150" x2="560" y2="150"/><line class="moving-line" x1="320" y1="22" x2="${bad?390:320}" y2="190"/><path class="right-angle" d="M320 150h28v-28"/><text x="356" y="130">${bad?'不是90°':'90°'}</text><text x="300" y="172">垂足 H</text></svg>`,distance:`<svg viewBox="0 0 640 210"><line x1="70" y1="165" x2="570" y2="165"/><circle cx="280" cy="35" r="8"/><text x="292" y="38">P</text><line class="distance-line" x1="280" y1="35" x2="${bad?450:280}" y2="165"/><circle cx="${bad?450:280}" cy="165" r="6"/><text x="300" y="110">${bad?'斜线段不是距离':'PH 最短'}</text></svg>`,transversal:`<svg viewBox="0 0 640 210"><line x1="80" y1="65" x2="560" y2="65"/><line x1="80" y1="155" x2="560" y2="155"/><line class="moving-line" x1="230" y1="10" x2="410" y2="200"/><text x="255" y="54">1</text><text x="348" y="83">2</text><text x="325" y="145">3</text><text x="405" y="175">4</text><text x="455" y="35">F · Z · U</text></svg>`,parallel:`<svg viewBox="0 0 640 210"><line x1="80" y1="65" x2="560" y2="65"/><line x1="80" y1="${bad?165:155}" x2="560" y2="${bad?145:155}"/><line class="moving-line" x1="220" y1="10" x2="410" y2="200"/><text x="430" y="55">${bad?'证据不足':'a ∥ b'}</text><text x="275" y="52">α</text><text x="365" y="145">${bad?'β':'α'}</text></svg>`,logic:`<div class="logic-flow"><span>题设</span><b>→</b><span>依据</span><b>→</b><span>${bad?'循环论证 ✕':'结论 ✓'}</span></div>`,translation:`<svg viewBox="0 0 640 210"><polygon points="130,155 210,155 165,70"/><polygon class="translated" points="390,155 470,155 425,70"/><line class="vector" x1="210" y1="110" x2="382" y2="110"/><text x="252" y="98">同方向 · 同距离</text></svg>`};return `<div class="math-demo geometry-demo"><p>${bad?'反例模式：检查必要条件':'拖动控制条，观察图形与数量关系'}</p>${diagrams[item.kind]}<label>改变角度 <output id="geoReadout">50°</output> <input id="geoControl" type="range" min="0" max="100" value="${bad?75:35}"></label><p>${item.rule}</p></div>`}
function extraMathVisual(){const item=deep.lessons[section],bad=stage===3;const diagrams={root:`<svg viewBox="0 0 640 180"><rect class="shape-fill" x="90" y="35" width="110" height="110"/><text x="112" y="95">面积 a</text><text x="245" y="95">边长 = ${bad?'±√a ?':'√a'}</text><path class="vector" d="M205 90h115"/></svg>`,coordinate:`<svg viewBox="0 0 640 180"><line x1="80" y1="90" x2="560" y2="90"/><line x1="320" y1="15" x2="320" y2="165"/><circle class="moving-point" cx="430" cy="45" r="9"/><text x="442" y="43">P(${bad?'b,a':'a,b'})</text><text x="540" y="112">x</text><text x="335" y="25">y</text></svg>`,equation:`<svg viewBox="0 0 640 180"><line x1="80" y1="145" x2="560" y2="35"/><line class="moving-line" x1="100" y1="30" x2="540" y2="155"/><circle cx="320" cy="90" r="9"/><text x="338" y="85">${bad?'只满足一个方程':'公共解 (x,y)'}</text></svg>`,inequality:`<svg viewBox="0 0 640 180"><line x1="70" y1="90" x2="570" y2="90"/><circle cx="300" cy="90" r="11"/><line class="range-line" x1="300" y1="90" x2="${bad?160:520}" y2="90"/><text x="280" y="125">${bad?'边界遗漏':'边界值'}</text></svg>`,stats:`<div class="bar-chart"><i style="height:42%"></i><i style="height:76%"></i><i style="height:${bad?'95':'58'}%"></i><i style="height:88%"></i><span>${bad?'有偏样本/误导纵轴':'比较、变化、构成'}</span></div>`};return `<div class="math-demo geometry-demo"><p>${bad?'反例模式：看清规则边界':'拖动控制条，观察表示与结果同步变化'}</p>${diagrams[item.kind]}<label>改变条件 <input id="geoControl" type="range" min="0" max="100" value="${bad?78:42}"></label><p>${item.rule}</p></div>`}
function physicsDeepVisual(){const item=deep.lessons[section],bad=stage===3,diagram=window.physicsDiagram(item.kind,bad).replace(/(physics-moving|wave-path|temp-path|ray|liquid|force-up|pressure-arrows|lever)/,'$1 experiment-object');return `<div class="physics-demo science-demo"><p>${bad?'反例模式：实验条件或读数存在错误':'控制变量：一次只改变一个条件'}</p><div class="physics-canvas ${item.kind}">${diagram}</div><label>改变实验条件 <input id="geoControl" type="range" min="0" max="100" value="${bad?80:46}"></label><p>${item.rule}</p></div>`}
function englishDeepVisual(){const name=book.chapters[unit].sections[section],bad=stage===3;return `<div class="english-demo language-demo"><p>Listen · Speak · Read · Write</p><div class="speech-scene"><span>${bad?'I no understand it.':'What do you notice?'}</span><span>${bad?'Check word order ✕':'I notice the change. ✓'}</span></div><div class="sound-wave"><i></i><i></i><i></i><i></i><i></i></div><label>播放进度 <input id="geoControl" type="range" min="0" max="100" value="35"></label><p>${name}</p></div>`}
function verifiedVisual(){
 const item=verifiedLesson(),bad=stage===3;if(!item)return'';
 const shell=(prompt,answer,label,min,max,value,readout,note)=>`<div class="english-demo language-demo verified-demo"><p>${item.visual.label}</p><div class="speech-scene"><span id="verifiedPrompt">${prompt}</span><span id="verifiedAnswer">${answer}</span></div><label>${label} <input id="verifiedControl" type="range" min="${min}" max="${max}" value="${value}"><output id="verifiedReadout">${readout}</output></label><p>${note}</p></div>`;
 if(item.visual.kind==='greeting-clock')return shell('07:00 · 在校门口见到老师','Good morning, Ms Gao. ✓','一天中的时间',6,22,7,'07:00','先读时间，再判断对象与交流阶段。');
 if(item.visual.kind==='conversation-flow')return shell('1 问候：Hi, I’m Lin.','下一轮要回应并交换姓名','对话轮次',1,4,1,'1/4',bad?'反例：句子没有承接上一轮，交流会中断。':'问候 → 询问 → 回应 → 友好结束');
 if(item.visual.kind==='inventory-lab')return shell('拥有者：I · 数量：1','I have a bottle.','物品数量',1,4,1,'1件',bad?'反例检查：I has 与 two key 都不正确。':'拥有者决定 have/has，数量决定冠词或复数。');
 if(item.visual.kind==='position-lab')return shell('红帽子接触床面','The red hat is on the bed.','空间关系',1,3,1,'on',bad?'反例检查：不要把 inside、on top、below 混成同一个介词。':'关系变化时，in / on / under 必须同步变化。');
 if(item.visual.kind==='vowel-lab')return shell('a · bag','/æ/ · 口形较开','目标元音',1,5,1,'a /æ/',bad?'反例检查：字母名称音不等于单词中的实际声音。':'字母形 ↔ 词中音 ↔ 示例词对照听辨。');
 if(item.visual.kind==='yard-observer')return shell('近处 · 多个 · 6株胡萝卜苗','What are these? They’re carrot plants.','观察点',1,4,1,'近·复',bad?'反例检查：these 不能与 is、it 或单数名词混用。':'距离决定 this/that 系列，数量决定单复数链。');
 if(item.visual.kind==='farm-counter')return shell('初次计数：14只鸭','Fourteen ducks.','观察进度',1,4,1,'14',bad?'反例检查：树后新发现的鸭子也必须加入总数。':'新增证据会改变计数结论，报告必须同步修正。');
 if(item.visual.kind==='demonstrative-distance')return shell('近处 · 一个 · 兔子','This is a rabbit.','距离与数量',1,4,1,'this',bad?'反例检查：指示词、is/are 和名词单复数必须一起变化。':'近/远 × 单/复 = this、that、these、those。');
 if(item.visual.kind==='interview-card')return shell('字段：姓名','What’s your name? — I’m Peter.','采访字段',1,5,1,'姓名',bad?'反例检查：回答必须落入问题对应的信息字段。':'问题定义字段，回答提供数据，复述用于核验。');
 if(item.visual.kind==='profile-compare')return shell('比较字段：运动','Pauline: tennis · Peter: 未提供','资料字段',1,5,1,'运动',bad?'反例检查：共同点必须来自资料证据，不能靠猜。':'先提取字段，再比较相同与不同，最后写回复。');
 if(item.visual.kind==='be-agreement')return shell('主语：I','I am 13 years old.','主语类别',1,5,1,'am',bad?'反例检查：先找完整主语，不能被邻近名词干扰。':'I→am；he/she/it→is；you/we/they→are。');
 if(item.visual.kind==='family-tree')return shell('参照人物：Emma','Jack is Emma’s grandfather.','家庭树路径',1,5,1,'grandfather',bad?'反例检查：亲属称谓由参照人物和关系路径决定，不能按年龄或性别猜。':'先定参照人物，再沿父母—子女连线判断代际关系。');
 if(item.visual.kind==='family-evidence')return shell('行动：帮助检查作业','My sister is helpful.','证据链',1,5,1,'行动→特点',bad?'反例检查：没有具体行动的形容词不能证明人物特点。':'人物 + 可观察行动 + 特点，三项必须能够互相验证。');
 if(item.visual.kind==='do-possessive')return shell('主语：his sister · 动作：play tennis','Does his sister play tennis?','规则组合',1,5,1,'does + 原形',bad?'反例检查：does 已标记第三人称，后面的动词不能再加 -s。':'动作问句使用 do/does；归属关系使用名词所有格 ’s。');
 if(item.visual.kind==='school-map')return shell('目标：dining hall · 参照：art building','The dining hall is in front of the art building.','校园方位线索',1,5,1,'in front of',bad?'反例检查：目标与参照物交换后，前后关系会反转。':'目标 + 方位关系 + 参照物，三项共同构成可复原的位置。');
 if(item.visual.kind==='school-email')return shell('地点：sports field','位置：next to teachers’ building · 活动：morning exercises','邮件证据卡',1,4,1,'地点→位置→活动',bad?'反例检查：不能把 dining hall 的食物和 sports field 的升旗活动串到同一地点。':'按地点锁定位置、活动和理由，证据不能跨行。');
 if(item.visual.kind==='there-be-tour')return shell('设施：1个 sports field','There is a large sports field.','导览步骤',1,5,1,'There is',bad?'反例检查：there is/are 由后接名词数量决定，不能用 have 替代。':'先说明某处有什么，再用方位句指向下一站。');
 if(item.visual.kind==='subject-reason')return shell('Emma · favourite: history','Because it’s interesting to learn about the past.','采访证据',1,5,1,'学科→理由',bad?'反例检查：difficult 不自动等于 dislike，理由必须属于正确人物和学科。':'人物 + favourite subject + because 理由，三项一一对应。');
 if(item.visual.kind==='subject-value')return shell('Mike · music','learn songs / play instruments → happy → singer','学科价值链',1,5,1,'活动→能力→未来',bad?'反例检查：共同课程不等于共同偏好，人物证据不能串行。':'从课堂活动出发，连接感受、能力和可能的未来方向。');
 if(item.visual.kind==='conjunction-builder')return shell('信息关系：同向补充','English is important, and the teacher is nice.','逻辑关系',1,3,1,'and',bad?'反例检查：because 与 so 不应在同一句中重复标记因果。':'and 并列补充；but 对比转折；because 引出原因。');
 if(item.visual.kind==='club-choice')return shell('Emma · 兴趣：music','can sing · can’t play instruments → music club','学生资料卡',1,5,1,'兴趣+能力+目标',bad?'反例检查：一项 can’t 不能推出“不能参加任何社团”。':'同时比较兴趣、已有能力、想学能力和时间。');
 if(item.visual.kind==='club-ad')return shell('Alice · tells and acts out stories','Book club · act out stories · Tuesday · library · Bill','广告证据卡',1,5,1,'人物↔广告',bad?'反例检查：时间、地点和联系人必须来自同一则广告。':'人物需求与活动匹配后，还要核对时间、地点和联系人。');
 if(item.visual.kind==='can-lab')return shell('主语：she · 能力：play violin','She can play the violin.','can句型',1,5,1,'can + 原形',bad?'反例检查：can 后不加 to 或第三人称 -s，也不用 do/does。':'主语变化时 can 与后接动词原形保持不变。');
 if(item.visual.kind==='school-day-clock')return shell('06:15 · Peter is on duty','a quarter past six · get dressed → brush teeth → go','学校日时钟',1,6,1,'6:15',bad?'反例检查：past 表示已过当前整点，to 指向下一个整点。':'时刻、活动和先后顺序必须同时对应。');
 if(item.visual.kind==='timo-timetable')return shell('Helsinki · December · Tuesday','7:40 get up → 9:00 school → 14:15 ice hockey → 16:00 home','Timo时间表',1,6,1,'上午',bad?'反例检查：文本事实不能直接变成人物评价。':'用具体时刻、活动和持续时间比较不同学校日。');
 if(item.visual.kind==='time-question-stress')return shell('回答：At 9:30 p.m.','WHAT TIME does Tom GO to BED?','问句与重音',1,6,1,'具体时刻',bad?'反例检查：does 后用动词原形，内容词重读。':'先由答案类型选问词，再用重音突出人物、动作和时刻。');
 if(item.visual.kind==='rule-sign-lab')return shell('走廊 · 行为：run','Walk in the hallway. Don’t run.','校园规则场景',1,5,1,'走廊',bad?'反例检查：Don’t和must后都接动词原形。':'地点 → 行为 → 风险 → 禁止与替代行为。');
 if(item.visual.kind==='rule-impact-map')return shell('Alice · get up early','目的：按时到校 · 感受：压力','规则影响片段',1,5,1,'早起',bad?'反例检查：感受不能直接证明制定者动机。':'规则 → 可能目的 → 感受 → 可协商方案。');
 if(item.visual.kind==='modal-rule-lab')return shell('实验室 · 允许断电接线','You can connect the circuit with the power off.','规则强度',1,6,1,'can',bad?'反例检查：mustn’t是禁止，don’t have to是不必。':'许可、外部要求、强制义务、禁止和非必要必须区分。');
 if(item.visual.kind==='fitness-frequency-lab')return shell('周一、周三、周六跑步','She goes running three times a week.','七日运动记录',1,7,1,'3次/周',bad?'反例检查：How often问频率，不是单次时长。':'日期记录 → 次数/周期 → 精确频率 → 大致副词。');
 if(item.visual.kind==='fitness-benefit-map')return shell('静息心率76 · 踏步后124','Heart rate rises during exercise.','运动反应阶段',1,5,1,'运动后',bad?'反例检查：一次测量不能证明永久效果或作医学诊断。':'运动类型 → 身体/情绪变化 → 数据证据 → 有边界的建议。');
 if(item.visual.kind==='fitness-grammar-lab')return shell('Lily的篮球 · 每周使用5天','The basketball is hers. She often uses it.','归属与频率',1,6,1,'hers + often',bad?'反例检查：mine后不接名词，never不再与don’t连用。':'有名词用my类，独立替代用mine类；副词位置由谓语决定。');
 if(item.visual.kind==='food-choice-lab')return shell('Amy · 不吃肉 · 预算15元','I’d like vegetable noodles, please.','点餐需求',1,6,1,'蔬菜面 ¥12',bad?'反例检查：一般喜好用like，本次点餐用would like。':'人物需求 → 菜单菜品 → 份量与价格 → 复述确认。');
 if(item.visual.kind==='nutrition-evidence')return shell('每100ml含糖8g · 容量250ml','The bottle contains 20 g of sugar.','标签与份量',1,5,1,'20g/瓶',bad?'反例检查：每100毫升数据不能直接当作整瓶数据。':'标签基准 → 实际容量 → 总量换算 → 有边界的建议。');
 if(item.visual.kind==='noun-quantity-lab')return shell('食材：tomatoes · 可逐个计数','How many tomatoes do we need?','食物数量类型',1,6,1,'many + 复数',bad?'反例检查：many修饰可数复数，much修饰不可数。':'可数/不可数 → 限定词 → 单位或容器 → 精确数量。');
 if(item.visual.kind==='live-action-monitor')return shell('10:15 LIVE · Mia在车站','I’m waiting for the bus right now.','现场时间点',1,6,1,'动作进行中',bad?'反例检查：正在展开的动作需要be + 动词-ing，状态动词不能机械套用。':'人物 + 现场线索 + be + 动词-ing → 当前活动报告。');
 if(item.visual.kind==='life-sharing-evidence')return shell('Saturday 9:20 · 校园花园照片','We’re planting trees in the school garden.','图文证据卡',1,6,1,'事实匹配',bad?'反例检查：旧照片不能证明此刻活动，分享前还要检查隐私边界。':'照片事实 → 时间戳 → 说明文字 → 发布对象与回应。');
 if(item.visual.kind==='present-continuous-lab')return shell('主语：she · 动作：write · now','She is writing now.','句式与时间线索',1,7,1,'is + writing',bad?'反例检查：进行时不能遗漏be；日常习惯通常使用一般现在时。':'主语一致 → -ing拼写 → 语序变化 → 时间尺度。');
 if(item.visual.kind==='weather-station')return shell('上海 · 14:00 · 乌云与雨滴','It’s rainy and 22°C in Shanghai.','气象观测卡',1,7,1,'22°C · rainy',bad?'反例检查：当前观测与未来预报必须按时间分开。':'地点 → 时间 → 天气符号 → 温度 → 播报与提醒。');
 if(item.visual.kind==='weather-feeling-map')return shell('Anna · 9°C · windy','She feels cold, so she is wearing gloves.','天气影响证据',1,6,1,'条件→感受→行动',bad?'反例检查：一个人的感受不能代表所有人，也不能直接诊断疾病。':'测量条件 → 个人感受 → 活动选择 → 可调整方案。');
 if(item.visual.kind==='weather-progressive-lab')return shell('直播：雨量正在增加','It is raining harder now.','天气状态与过程',1,7,1,'is raining',bad?'反例检查：规律用一般现在时，当前过程用be + V-ing。':'天气状态 → 实时过程 → 人物活动 → 时间线索与时态。');
 if(item.visual.kind==='special-day-timeline')return shell('5 May · 10:00 · 科技馆','They were at the science museum.','过去经历节点',1,6,1,'were · 地点',bad?'反例检查：过去状态用was/were，过去动作需要自己的过去式。':'时间 → 地点 → 人物数量 → was/were → 感受。');
 if(item.visual.kind==='memory-evidence-chain')return shell('纸桥第一次承重200g','加三角支撑后承重450g','经历证据链',1,6,1,'+250g',bad?'反例检查：事件顺序和因果不能倒置，反思要有行动与结果。':'困难 → 调整 → 量化结果 → 可迁移的学习。');
 if(item.visual.kind==='past-be-lab')return shell('主语：they · 地点：museum','They were at the museum.','过去状态句式',1,6,1,'were',bad?'反例检查：was/were问句不再添加did。':'主语一致 → was/were → 否定或倒装 → 简答。');
 if(item.visual.kind==='story-plot-map')return shell('人物目标：狐狸想得到葡萄','He jumped but could not reach them.','故事情节节点',1,6,1,'目标→尝试→结果',bad?'反例检查：不能把结局后的说法倒推成最初目标。':'人物与背景 → 目标 → 冲突 → 行动 → 结局。');
 if(item.visual.kind==='story-theme-evidence')return shell('两人单独搬石头都失败','合作后用木杆抬起石头','主题证据',1,6,1,'合作→结果',bad?'反例检查：主题必须解释关键选择和后果，不能只挑一个名词。':'人物选择 → 可观察后果 → 主题解释 → 现实任务。');
 if(item.visual.kind==='simple-past-action-lab')return shell('动作：find · 肯定过去','She found the key.','过去动作句式',1,7,1,'found',bad?'反例检查：did已经标记过去，后面的动词必须恢复原形。':'规则/不规则过去式 → did问答 → 原形恢复 → 时态一致。');
 if(item.visual.kind==='animal-evidence')return shell('企鹅 · strong flippers · short legs','Penguins swim well because their flippers push water.','动物证据卡',1,5,1,'企鹅',bad?'反例检查：评价必须有结构或行为证据，单复数保持一致。':'结构 → 行为 → 形容词 → because理由。');
 if(item.visual.kind==='animal-role')return shell('导盲犬 · 避开障碍','trained behaviour → safer travel','动物作用证据链',1,5,1,'导盲犬',bad?'反例检查：保护口号不能代替对象、步骤和结果。':'作用 → 风险 → 行动，每一步都回到证据。');
 if(item.visual.kind==='animal-language-lab')return shell('答案：In mountain forests.','Where do pandas live?','所需信息',1,7,1,'Where',bad?'反例检查：先看答案类型，再核对do/does与复数。':'地点、原因、数量、方式分别选择对应Wh问词。');
 if(item.visual.kind==='birthday-calendar')return shell('Helen · 3rd December','When is Helen’s birthday? — It’s on 3rd December.','人物与购物项目',1,7,1,'Helen',bad?'反例检查：不能把生日和年龄混淆；总额必须乘数量。':'日期问答与购物小计都须对应同一条证据。');
 if(item.visual.kind==='birthday-posts')return shell('Xiaoming · 13th June · 每年','在村里的大树下拍家庭照 → 保存共同回忆','人物与时间',1,6,1,'Xiaoming',bad?'反例检查：两位发帖者的活动与今年计划不能交换。':'人物→日期→活动→理由→新计划，逐条核对原帖。');
 if(item.visual.kind==='ordinal-calendar')return shell('第11天 · 7月','on 11th July · eleven→eleventh','日历日期',1,10,1,'11th',bad?'反例检查：11/12/13 无论最后一位是什么都用 th。':'先查最后两位11—13，再由最后一位选st/nd/rd/th。');
 return shell('A /eɪ/','序号 1 · A as in apple','字母序号',1,26,1,'1/26',bad?'反例：名称音相近时不能靠猜，要复述确认。':'字母形 ↔ 名称音 ↔ 序号一一对应');
}
function activateVerifiedVisual(){
 const item=verifiedLesson(),control=$('verifiedControl'),prompt=$('verifiedPrompt'),answer=$('verifiedAnswer'),readout=$('verifiedReadout');if(!item||!control)return;
 if(item.visual.kind==='greeting-clock'){control.oninput=()=>{const hour=+control.value,greeting=hour<12?'Good morning':hour<18?'Good afternoon':'Good evening';readout.textContent=String(hour).padStart(2,'0')+':00';prompt.textContent=`${readout.textContent} · 见面问候`;answer.textContent=`${greeting}! ✓`}}
 else if(item.visual.kind==='conversation-flow'){const turns=[['1 问候：Hi, I’m Lin.','下一轮要回应并交换姓名'],['2 询问：What’s your name?','直接问句使用 What + is + 主语'],['3 回应：My name is Sam.','提供对方刚刚请求的信息'],['4 结束：Nice to meet you, too.','too 承接上一句的友好表达']];control.oninput=()=>{const i=+control.value-1;readout.textContent=`${i+1}/4`;prompt.textContent=turns[i][0];answer.textContent=turns[i][1]}}
 else if(item.visual.kind==='inventory-lab'){const rows=[['1件','拥有者：I · 数量：1','I have a bottle.'],['2件','拥有者：I · 数量：2','I have two erasers.'],['3件','拥有者：Ella · 数量：3','Ella has three keys.'],['4件','拥有者：They · 数量：4','They have four bottles.']];control.oninput=()=>{const row=rows[+control.value-1];readout.textContent=row[0];prompt.textContent=row[1];answer.textContent=row[2]}}
 else if(item.visual.kind==='position-lab'){const rows=[['on','红帽子接触床面','The red hat is on the bed.'],['in','橡皮在盒子内部','The eraser is in the box.'],['under','两把钥匙在书桌下方','The keys are under the desk.']];control.oninput=()=>{const row=rows[+control.value-1];readout.textContent=row[0];prompt.textContent=row[1];answer.textContent=row[2]}}
 else if(item.visual.kind==='vowel-lab'){const rows=[['a /æ/','a · bag','/æ/ · 口形较开'],['e /e/','e · desk','/e/ · 舌位稍高'],['i /ɪ/','i · six','/ɪ/ · 短而放松'],['o /ɒ/','o · box','/ɒ/ · 圆唇开口'],['u /ʌ/','u · cup','/ʌ/ · 短促放松']];control.oninput=()=>{const row=rows[+control.value-1];readout.textContent=row[0];prompt.textContent=row[1];answer.textContent=row[2]}}
 else if(item.visual.kind==='yard-observer'){const rows=[['近·复','近处 · 多个 · 6株胡萝卜苗','What are these? They’re carrot plants.'],['远·单','远处 · 一个 · 1只鸭','What’s that? It’s a duck.'],['远·复','远处 · 多个 · 10棵苹果树','What are those? They’re apple trees.'],['数量','重新计数 · 12只兔子','How many rabbits can you see? I can see twelve.']];control.oninput=()=>{const row=rows[+control.value-1];readout.textContent=row[0];prompt.textContent=row[1];answer.textContent=row[2]}}
 else if(item.visual.kind==='farm-counter'){const rows=[['14','初次计数：14只鸭','Fourteen ducks.'],['+1','发现树后还有1只鸭','Another duck is behind the tree.'],['15','修正总数：14 + 1','His uncle has fifteen ducks.'],['复核','分区检查湖边、草地和树后','No animal is missed or counted twice.']];control.oninput=()=>{const row=rows[+control.value-1];readout.textContent=row[0];prompt.textContent=row[1];answer.textContent=row[2]}}
 else if(item.visual.kind==='demonstrative-distance'){const rows=[['this','近处 · 一个 · 兔子','This is a rabbit.'],['that','远处 · 一个 · 房子','That is a house.'],['these','近处 · 多个 · 花','These are flowers.'],['those','远处 · 多个 · 马','Those are horses.']];control.oninput=()=>{const row=rows[+control.value-1];readout.textContent=row[0];prompt.textContent=row[1];answer.textContent=row[2]}}
 else if(item.visual.kind==='interview-card'){const rows=[['姓名','字段：姓名','What’s your name? — I’m Peter.'],['年龄','字段：年龄','How old are you? — I’m 12.'],['国家','字段：来自哪里','Where are you from? — I’m from the UK.'],['班级','字段：班级','What class are you in? — Class 1, Grade 7.'],['班主任','字段：班主任','Who’s your class teacher? — It’s Ms Gao.']];control.oninput=()=>{const row=rows[+control.value-1];readout.textContent=row[0];prompt.textContent=row[1];answer.textContent=row[2]}}
 else if(item.visual.kind==='profile-compare'){const rows=[['运动','比较字段：运动','Pauline: tennis · Peter: 未提供'],['宠物','比较字段：宠物','Pauline: parrot · Peter: 未提供'],['音乐','比较字段：音乐','Pauline: 未提供 · Peter: guitar'],['居住地','比较字段：居住地','Pauline: Singapore · Peter: Beijing'],['共同点','你的兴趣与资料求交集','只选择有文本证据的共同点']];control.oninput=()=>{const row=rows[+control.value-1];readout.textContent=row[0];prompt.textContent=row[1];answer.textContent=row[2]}}
 else if(item.visual.kind==='be-agreement'){const rows=[['am','主语：I','I am 13 years old.'],['is','主语：Peter / he','Peter is from the UK.'],['is','主语：Sally / she','She is my new friend.'],['are','主语：you / we / they','They are in Class 1.'],['are','主语：Tom and I','Tom and I are in the band.']];control.oninput=()=>{const row=rows[+control.value-1];readout.textContent=row[0];prompt.textContent=row[1];answer.textContent=row[2]}}
 else if(item.visual.kind==='family-tree'){const rows=[['grandfather','参照人物：Emma','Jack is Emma’s grandfather.'],['grandmother','参照人物：Emma','Linda is Emma’s grandmother.'],['uncle','参照人物：Emma','Tom is Emma’s uncle.'],['mother','参照人物：Emma','Alice is Emma’s mother.'],['sister','参照人物：Tom','Alice is Tom’s sister.']];control.oninput=()=>{const row=rows[+control.value-1];readout.textContent=row[0];prompt.textContent=row[1];answer.textContent=row[2]}}
 else if(item.visual.kind==='family-evidence'){const rows=[['行动→特点','行动：帮助检查作业','My sister is helpful.'],['行动→特点','行动：耐心听我解释','My mother is patient.'],['行动→特点','行动：讲故事让大家笑','My grandpa is funny.'],['共同活动→氛围','周末一起做饭和交谈','Our family is close.'],['观点+证据','把特点和行动连成 because 句','I like her because she always listens.']];control.oninput=()=>{const row=rows[+control.value-1];readout.textContent=row[0];prompt.textContent=row[1];answer.textContent=row[2]}}
 else if(item.visual.kind==='do-possessive'){const rows=[['does + 原形','主语：his sister · 动作：play tennis','Does his sister play tennis?'],['do + 原形','主语：your parents · 动作：cook','Do your parents cook together?'],['简短回答','回答上一问：肯定','Yes, they do.'],['所有格 ’s','所有者：father · 物品：guitar','It is my father’s guitar.'],['’s = is','主语：father · 特点：funny','My father’s funny.']];control.oninput=()=>{const row=rows[+control.value-1];readout.textContent=row[0];prompt.textContent=row[1];answer.textContent=row[2]}}
 else if(item.visual.kind==='school-map'){const rows=[['in front of','目标：dining hall · 参照：art building','The dining hall is in front of the art building.'],['behind','目标：classroom building · 参照：sports field','The classroom building is behind the sports field.'],['across from','目标：teachers’ building · 参照：school hall','The teachers’ building is across from the school hall.'],['between','目标：student centre · 两个参照','It is between the library and the gym.'],['next to','目标：smart whiteboard · 参照：blackboard','The smart whiteboard is next to the blackboard.']];control.oninput=()=>{const row=rows[+control.value-1];readout.textContent=row[0];prompt.textContent=row[1];answer.textContent=row[2]}}
 else if(item.visual.kind==='school-email'){const rows=[['地点→位置→活动','地点：sports field','next to teachers’ building · exercises / flag-raising'],['地点→位置→活动','地点：classroom building','behind sports field · study / change seats weekly'],['地点→位置→活动','地点：dining hall','across from sports field · eat lunch'],['观点→理由','最喜欢的地点：dining hall','many kinds of food · delicious jiaozi']];control.oninput=()=>{const row=rows[+control.value-1];readout.textContent=row[0];prompt.textContent=row[1];answer.textContent=row[2]}}
 else if(item.visual.kind==='there-be-tour'){const rows=[['There is','设施：1个 sports field','There is a large sports field.'],['There are','设施：多棵 trees','There are some trees in front of it.'],['Is there','确认：1个 dining hall','Is there a dining hall? Yes, there is.'],['Are there','确认：多个 lockers','Are there any lockers? No, there aren’t.'],['路线','下一站：classroom building','The building is behind the sports field. Let’s go!']];control.oninput=()=>{const row=rows[+control.value-1];readout.textContent=row[0];prompt.textContent=row[1];answer.textContent=row[2]}}
 else if(item.visual.kind==='subject-reason'){const rows=[['学科→理由','Emma · favourite: history','Because it’s interesting to learn about the past.'],['学科→理由','Meimei · favourite: English','Because it’s useful and the teacher is nice.'],['学科→理由','Binbin · favourite: maths','Because he’s good with numbers.'],['负面态度','Ella · doesn’t like history','Because she thinks it’s hard.'],['采访转述','同学原话：My favourite is music.','Her favourite subject is music.']];control.oninput=()=>{const row=rows[+control.value-1];readout.textContent=row[0];prompt.textContent=row[1];answer.textContent=row[2]}}
 else if(item.visual.kind==='subject-value'){const rows=[['活动→感受→未来','Mike · music','songs / instruments → happy → singer'],['活动→能力→未来','Binbin · maths','work out problems → logical thinking → scientist'],['共同课程','Mike ∩ Binbin','maths · history · English · IT'],['区别偏好','两人 favourite 不同','Mike: music · Binbin: maths'],['个人迁移','你的学科与课堂活动','用具体活动说明能力，不只写 useful']];control.oninput=()=>{const row=rows[+control.value-1];readout.textContent=row[0];prompt.textContent=row[1];answer.textContent=row[2]}}
 else if(item.visual.kind==='conjunction-builder'){const rows=[['and','关系：同向补充','English is important, and the teacher is nice.'],['but','关系：对比转折','Biology is difficult but important.'],['because','关系：结论←原因','I like Chinese because it is fun.']];control.oninput=()=>{const row=rows[+control.value-1];readout.textContent=row[0];prompt.textContent=row[1];answer.textContent=row[2]}}
 else if(item.visual.kind==='club-choice'){const rows=[['兴趣+能力+目标','Emma · music','can sing · can’t play instruments → music club'],['已有能力','Peter · guitar','can play guitar → music club'],['学习目标','Sam · interested in chess','can’t play yet → learn in chess club'],['兴趣+证据','Maya · nature','can read maps → nature club'],['时间条件','Sunday afternoon available','matches nature club meeting time']];control.oninput=()=>{const row=rows[+control.value-1];readout.textContent=row[0];prompt.textContent=row[1];answer.textContent=row[2]}}
 else if(item.visual.kind==='club-ad'){const rows=[['人物↔广告','Alice · tells and acts out stories','Book club · Tuesday · library · Bill'],['人物↔广告','Lin Hui · nature / maps','Nature club · Sunday · Jenny'],['人物↔广告','Jack · wants to cook','Cooking club · Wednesday 4:30 · Room 303'],['字段核对','Book club contact','Bill · not Jenny or Ma Xiaohui'],['申请目标','已有能力 + 困难 + 想学内容','Can I join your club?']];control.oninput=()=>{const row=rows[+control.value-1];readout.textContent=row[0];prompt.textContent=row[1];answer.textContent=row[2]}}
 else if(item.visual.kind==='can-lab'){const rows=[['can + 原形','主语：she · ability: play violin','She can play the violin.'],['can + 原形','主语：they · ability: play chess','They can play chess.'],['Can…?','一般疑问：Ella / play violin','Can Ella play the violin?'],['can’t + 原形','Emma / play instruments','Emma can’t play instruments.'],['互补能力','Leo builds · Mia programs','They can work together.']];control.oninput=()=>{const row=rows[+control.value-1];readout.textContent=row[0];prompt.textContent=row[1];answer.textContent=row[2]}}
 else if(item.visual.kind==='school-day-clock'){const rows=[['6:15','06:15 · Peter is on duty','a quarter past six · get dressed'],['6:30','06:30 · usual morning','half past six · get up'],['6:50','06:50 · breakfast','ten to seven · have breakfast'],['6:45','06:45 · Tom','a quarter to seven · get up'],['7:50','07:50 · Tom','ten to eight · go to school'],['9:30 p.m.','21:30 · Tom','half past nine · go to bed']];control.oninput=()=>{const row=rows[+control.value-1];readout.textContent=row[0];prompt.textContent=row[1];answer.textContent=row[2]}}
 else if(item.visual.kind==='timo-timetable'){const rows=[['上午','7:40 get up · 10-minute walk','9:00 school · 45-minute lessons'],['午间','12:00 lunch','12:30 afternoon lessons begin'],['下午','14:15 lessons finish','ice hockey club'],['傍晚','16:00 home · already dark','18:00 dinner'],['晚间','after dinner','read for one hour · prepare schoolbag'],['结束','21:30','go to bed']];control.oninput=()=>{const row=rows[+control.value-1];readout.textContent=row[0];prompt.textContent=row[1];answer.textContent=row[2]}}
 else if(item.visual.kind==='time-question-stress'){const rows=[['具体时刻','回答：At 9:30 p.m.','WHAT TIME does Tom GO to BED?'],['时间范围','回答：On Monday afternoons.','WHEN do they GO to the MUSIC CLUB?'],['活动内容','回答：He brushes his teeth.','WHAT does Peter DO before BREAKFAST?'],['第三人称','Tom / go to bed','What time DOES Tom GO to bed?'],['时间介词','7:30 · Monday · December','AT 7:30 · ON Monday · IN December'],['对比重音','不是六点，是七点','I get up at SEVEN.']];control.oninput=()=>{const row=rows[+control.value-1];readout.textContent=row[0];prompt.textContent=row[1];answer.textContent=row[2]}}
 else if(item.visual.kind==='rule-sign-lab'){const rows=[['走廊','地点：hallway · 风险：转角碰撞','Walk in the hallway. Don’t run.'],['图书馆','地点：library · 目标：阅读','We must keep quiet.'],['教室','地点：classroom · 行为：eat','We can’t eat in class.'],['餐厅','地点：dining hall · 行为：wait','Wait in line. Don’t push.'],['实验室','地点：lab · 风险：湿手触线','Wear goggles. Don’t touch wires with wet hands.']];control.max=rows.length;control.oninput=()=>{const row=rows[+control.value-1];readout.textContent=row[0];prompt.textContent=row[1];answer.textContent=row[2]}}
 else if(item.visual.kind==='rule-impact-map'){const rows=[['早起','Alice has to get up early.','目的：按时到校 · 方案：制定晨间表'],['整理房间','Alice has to make her bed.','目的：管理空间 · 方案：明确完成标准'],['先作业','She must do homework before relaxing.','记录用时 · 讨论现实的休息安排'],['手机规则','Eric must put his phone away by 9.','记录睡眠和作业 · 一周后复盘'],['回信结构','感受 → 目的 → 证据 → 建议','I understand… Try… Record… Discuss…']];control.max=rows.length;control.oninput=()=>{const row=rows[+control.value-1];readout.textContent=row[0];prompt.textContent=row[1];answer.textContent=row[2]}}
 else if(item.visual.kind==='modal-rule-lab'){const rows=[['can','允许：断电时连接电路','You can connect it with the power off.'],['can’t','不允许：课堂进食','We can’t eat in class.'],['have to','外部要求：8点前到校','We have to arrive before 8:00.'],['must','强制义务：通电前检查','You must check the circuit.'],['mustn’t','严禁：湿手触线','You mustn’t touch wires with wet hands.'],['don’t have to','非必要：自带护目镜','You don’t have to bring goggles.']];control.max=rows.length;control.oninput=()=>{const row=rows[+control.value-1];readout.textContent=row[0];prompt.textContent=row[1];answer.textContent=row[2]}}
 else if(item.visual.kind==='fitness-frequency-lab'){const rows=[['3次/周','Mia：周一、周三、周六跑步','She goes running three times a week.'],['2次/周','篮球：周二、周五','I play basketball twice a week.'],['1次/周','游泳：周日','I swim once a week.'],['每天','拉伸：周一至周日','I stretch every day.'],['usually','六天步行上学','He usually walks to school.'],['sometimes','一天骑车','He sometimes rides a bike.'],['never','七天均无该活动','He never plays tennis.']];control.max=rows.length;control.oninput=()=>{const row=rows[+control.value-1];readout.textContent=row[0];prompt.textContent=row[1];answer.textContent=row[2]}}
 else if(item.visual.kind==='fitness-benefit-map'){const rows=[['静息','测量15秒脉搏×4','Resting heart rate: 76 bpm.'],['运动后','原地踏步2分钟','Heart rate rises to 124 bpm.'],['恢复','休息3分钟','It falls toward 88 bpm.'],['情绪','骑车30分钟后更平静','Cycling may help Ana relax.'],['安全边界','逐步增加强度；尖锐疼痛时停止','Benefits depend on type, dose and recovery.']];control.max=rows.length;control.oninput=()=>{const row=rows[+control.value-1];readout.textContent=row[0];prompt.textContent=row[1];answer.textContent=row[2]}}
 else if(item.visual.kind==='fitness-grammar-lab'){const rows=[['hers + often','Lily的篮球 · 每周使用5天','The basketball is hers. She often uses it.'],['ours + sometimes','我们的跳绳 · 每周使用2天','The rope is ours. We sometimes use it.'],['my / mine','我的球拍','This is my racket. The racket is mine.'],['her / hers','她的自行车','This is her bike. The bike is hers.'],['实义动词前','他经常打网球','He often plays tennis.'],['be动词后','他经常精力充沛','He is often energetic.']];control.max=rows.length;control.oninput=()=>{const row=rows[+control.value-1];readout.textContent=row[0];prompt.textContent=row[1];answer.textContent=row[2]}}
 else if(item.visual.kind==='food-choice-lab'){const rows=[['蔬菜面 ¥12','Amy · 不吃肉 · 预算15元','I’d like vegetable noodles, please.'],['鸡肉饭 ¥15','Ben · 想吃米饭','I’d like chicken rice, please.'],['汤 ¥6','Cindy · 只要汤','I’d like some soup, please.'],['小杯果汁','询问饮料与份量','Would you like a small glass of juice?'],['¥33','三人午餐总价','12 + 15 + 6 = 33 yuan.'],['复述确认','菜名、数量、限制','Is that right?']];control.max=rows.length;control.oninput=()=>{const row=rows[+control.value-1];readout.textContent=row[0];prompt.textContent=row[1];answer.textContent=row[2]}}
 else if(item.visual.kind==='nutrition-evidence'){const rows=[['20g/瓶','每100ml含糖8g · 容量250ml','8 × 2.5 = 20 g'],['18g/瓶','每100ml含糖6g · 容量300ml','6 × 3 = 18 g'],['早餐','甜饮+饼干','Add an egg and fruit; choose water.'],['午餐对比','米饭鱼青菜水 / 炸物甜饮','Compare food groups, portions and frequency.'],['一周计划','三天用水替代甜饮','Record the drink and volume each day.']];control.max=rows.length;control.oninput=()=>{const row=rows[+control.value-1];readout.textContent=row[0];prompt.textContent=row[1];answer.textContent=row[2]}}
 else if(item.visual.kind==='noun-quantity-lab'){const rows=[['many + 复数','tomatoes · 可逐个计数','How many tomatoes do we need?'],['much + 不可数','cheese · 需质量单位','How much cheese do we need?'],['some','肯定句：eggs','We have some eggs.'],['any','否定句：milk','We don’t have any milk.'],['容器量词','milk · 两瓶','two bottles of milk'],['比例换算','两人份→四人份','200 g rice → 400 g rice']];control.max=rows.length;control.oninput=()=>{const row=rows[+control.value-1];readout.textContent=row[0];prompt.textContent=row[1];answer.textContent=row[2]}}
 else if(item.visual.kind==='live-action-monitor'){const rows=[['动作进行中','10:15 LIVE · Mia在车站','I’m waiting for the bus right now.'],['is cooking','爸爸系围裙 · 锅在冒热气','Dad is cooking dinner.'],['is taking','妹妹拿着相机','She is taking photos.'],['are playing','两名学生在球场','They are playing badminton.'],['is moving right','小车0秒0cm→1秒4cm','The car is moving to the right.'],['is moving faster','相邻位移4cm→7cm','It is moving faster.']];control.max=rows.length;control.oninput=()=>{const row=rows[+control.value-1];readout.textContent=row[0];prompt.textContent=row[1];answer.textContent=row[2]}}
 else if(item.visual.kind==='life-sharing-evidence'){const rows=[['事实匹配','Saturday 9:20 · 戴手套拿树苗','We’re planting trees in the school garden.'],['时间错配','旧照片：last Sunday','It does not prove what they are doing now.'],['合适回应','班级群 · 校园活动','Great work! Where are you planting?'],['隐私检查','包含电话与精确实时位置','Remove unnecessary personal information.'],['图书馆活动','16:10 · 整理书架','We are putting books on the shelves.'],['发布前核对','事实、时间、同意、对象','Share necessary information with permission.']];control.max=rows.length;control.oninput=()=>{const row=rows[+control.value-1];readout.textContent=row[0];prompt.textContent=row[1];answer.textContent=row[2]}}
 else if(item.visual.kind==='present-continuous-lab'){const rows=[['is + writing','she · write · now','She is writing now.'],['aren’t + watching','they · 否定','They aren’t watching a game.'],['Are … watching?','they · 一般疑问','Are they watching a game?'],['making','make · 去e','make → making'],['running','run · 双写n','run → running'],['lying','lie · ie变y','lie → lying'],['习惯/当前','every day / now','He walks every day; he is walking now.']];control.max=rows.length;control.oninput=()=>{const row=rows[+control.value-1];readout.textContent=row[0];prompt.textContent=row[1];answer.textContent=row[2]}}
 else if(item.visual.kind==='weather-station'){const rows=[['22°C · rainy','上海 · 14:00 · 乌云与雨滴','It’s rainy in Shanghai at 2 p.m.'],['8°C · windy','北京 · 有风','It’s windy and cool in Beijing.'],['26°C · sunny','广州 · 晴','It’s sunny and warm in Guangzhou.'],['12°C · foggy','校园 · 7:30','It is foggy and cool now.'],['20°C · sunny','校园 · 午后预报','It will be sunny this afternoon.'],['+5°C','8时12°C→11时17°C','The temperature is rising.'],['−3°C','14时21°C→17时18°C','The temperature is falling.']];control.max=rows.length;control.oninput=()=>{const row=rows[+control.value-1];readout.textContent=row[0];prompt.textContent=row[1];answer.textContent=row[2]}}
 else if(item.visual.kind==='weather-feeling-map'){const rows=[['条件→感受→行动','Anna · 9°C · windy','She feels cold, so she is wearing gloves.'],['不同选择','28°C · sunny · Ben/Mei','Ben swims; Mei chooses shade indoors.'],['改时间','周六上午小雨→下午晴','Move the ride to the sunny afternoon.'],['因果句','rain · stay inside','Because it is raining, we are staying inside.'],['强风时段','10°C · 25 km/h','Choose layers and a sheltered place.'],['较适合时段','16°C · 6 km/h','The afternoon may suit the team better.']];control.max=rows.length;control.oninput=()=>{const row=rows[+control.value-1];readout.textContent=row[0];prompt.textContent=row[1];answer.textContent=row[2]}}
 else if(item.visual.kind==='weather-progressive-lab'){const rows=[['is raining','雨正在下','It is raining now.'],['rainy','天气状态','It is rainy today.'],['isn’t snowing','当前否定','It isn’t snowing.'],['Is it snowing?','一般疑问','No, it isn’t.'],['often rains','夏季规律','It often rains here in summer.'],['is falling','温度18°C→14°C','The temperature is falling.'],['is getting heavier','雨量0→4 mm','The rain is getting heavier.']];control.max=rows.length;control.oninput=()=>{const row=rows[+control.value-1];readout.textContent=row[0];prompt.textContent=row[1];answer.textContent=row[2]}}
 else if(item.visual.kind==='special-day-timeline'){const rows=[['were · 地点','5 May 10:00 · Lily和父母','They were at the science museum.'],['was curious','Lily · 科技馆','Lily was curious and happy.'],['was nervous','比赛前 · Tom','Tom was nervous before the match.'],['were proud','比赛后 · 队友','They were proud after the match.'],['12°C','9:00 · 山脚','Mia was nervous at the foot of the hill.'],['18°C','15:00 · 观景台','They were excited at the viewpoint.']];control.max=rows.length;control.oninput=()=>{const row=rows[+control.value-1];readout.textContent=row[0];prompt.textContent=row[1];answer.textContent=row[2]}}
 else if(item.visual.kind==='memory-evidence-chain'){const rows=[['+250g','纸桥200g→450g','The second bridge held 250 g more.'],['困难','Ben不敢介绍旧书','Ben was shy at first.'],['行动','示范后完成3次介绍','He practised three introductions.'],['结果','信心提升','Practice and support built confidence.'],['迷路','返回最后路标并求助','They learned to check signs and ask for help.'],['模型车','调整轮距→直行3m','Change one variable and test again.']];control.max=rows.length;control.oninput=()=>{const row=rows[+control.value-1];readout.textContent=row[0];prompt.textContent=row[1];answer.textContent=row[2]}}
 else if(item.visual.kind==='past-be-lab'){const rows=[['were','they · museum','They were at the museum.'],['weren’t','过去否定','They weren’t at the museum.'],['Were…?','一般疑问','Were they at the museum?'],['was','Leo · library','Leo was in the library.'],['Where was…?','询问地点','Where was Leo?'],['was vs visited','状态/动作','She was happy. She visited the museum.']];control.max=rows.length;control.oninput=()=>{const row=rows[+control.value-1];readout.textContent=row[0];prompt.textContent=row[1];answer.textContent=row[2]}}
 else if(item.visual.kind==='story-plot-map'){const rows=[['目标','狐狸想要葡萄','The fox wanted the grapes.'],['尝试','跳了几次','He jumped several times.'],['结果','没有够到','He could not reach them.'],['背景限制','暴风雪山路','They looked for shelter.'],['救助小鸟','发现→照顾→联系→放飞','The bird recovered and flew away.'],['科学史','问题→假设→实验→结果','Evidence changed the model.']];control.max=rows.length;control.oninput=()=>{const row=rows[+control.value-1];readout.textContent=row[0];prompt.textContent=row[1];answer.textContent=row[2]}}
 else if(item.visual.kind==='story-theme-evidence'){const rows=[['合作','单独失败→一起成功','Cooperation solved the problem.'],['诚信','归还钱包→建立信任','Honesty built trust.'],['信任下降','两次谎报→真话无人信','Repeated lies destroyed trust.'],['主题≠道具','故事出现石头','A stone is not the theme.'],['实验迁移','遗漏3项→交叉检查后0项','Clear roles reduced missing records.'],['证据边界','一次成功','One result does not prove always.']];control.max=rows.length;control.oninput=()=>{const row=rows[+control.value-1];readout.textContent=row[0];prompt.textContent=row[1];answer.textContent=row[2]}}
 else if(item.visual.kind==='simple-past-action-lab'){const rows=[['found','find · 肯定过去','She found the key.'],['didn’t find','过去否定','She didn’t find it in her bag.'],['Did…find?','一般疑问','Did she find the key?'],['played/lived','规则变化','play→played; live→lived'],['stopped/studied','双写/辅音+y','stop→stopped; study→studied'],['went/saw/took','不规则过去式','go→went; see→saw; take→took'],['measured/fell','实验记录','They measured both cups; the temperature fell.']];control.max=rows.length;control.oninput=()=>{const row=rows[+control.value-1];readout.textContent=row[0];prompt.textContent=row[1];answer.textContent=row[2]}}
 else if(item.visual.kind==='animal-evidence'){const rows=[['企鹅','结构：strong flippers · short legs','Penguins swim well because their flippers push water.'],['大象','结构：trunk · large ears','Elephants use their trunks to carry and communicate.'],['海豚','结构：smooth body · fins','Dolphins swim and communicate in groups.'],['水獭','结构：webbed feet · thick fur','Otters swim well and keep warm in water.'],['老虎','结构：strong legs · sharp claws','Tigers are powerful hunters; observe from a safe distance.']];control.max=rows.length;control.oninput=()=>{const row=rows[+control.value-1];readout.textContent=row[0];prompt.textContent=row[1];answer.textContent=row[2]}}
 else if(item.visual.kind==='animal-role'){const rows=[['导盲犬','作用：避开障碍，帮助安全出行','证据链：trained behaviour → safer travel'],['蜜蜂','作用：搬运花粉，帮助植物结实','证据链：pollination → seeds and fruit'],['海龟','风险：塑料袋像水母，可能被误食','行动：减塑 + 清理海滩'],['水鸟','风险：河岸垃圾和水体污染','行动：固定路线调查 + 清理 + 复测'],['校园昆虫','花园12只 · 硬化地面2只','谨慎结论：花源可能影响出现数量，还需控制时间']];control.max=rows.length;control.oninput=()=>{const row=rows[+control.value-1];readout.textContent=row[0];prompt.textContent=row[1];answer.textContent=row[2]}}
 else if(item.visual.kind==='animal-language-lab'){const rows=[['Where','答案：In mountain forests.','Where do pandas live?'],['Why','答案：Because they need water.','Why do they stay near rivers?'],['How many','答案：About twenty.','How many animals are there?'],['How','答案：It moves quietly.','How does it move?'],['单数','a koala / eat leaves','What does a koala eat?'],['复数','koalas / eat leaves','What do koalas eat?'],['不规则复数','one mouse → three mice','How many mice are there?']];control.max=rows.length;control.oninput=()=>{const row=rows[+control.value-1];readout.textContent=row[0];prompt.textContent=row[1];answer.textContent=row[2]}}
 else if(item.visual.kind==='birthday-calendar'){const rows=[['Helen','Helen · 3rd December','When is Helen’s birthday? — It’s on 3rd December.'],['Fu Xing','Fu Xing · 22nd August','When is Fu Xing’s birthday? — It’s on 22nd August.'],['父亲','Teng Fei’s father · 9th January','A birthday card is a possible gift.'],['Ms Gao','Ms Gao · 12th June','The class can sing a song for her.'],['蛋糕','蛋糕 · 85元 · 1个','85 × 1 = 85元'],['橙子','橙子 · 6元/千克 · 5千克','6 × 5 = 30元'],['酸奶与总额','酸奶 · 5元/瓶 · 10瓶','5 × 10 = 50元；总额85+30+50=165元']];control.oninput=()=>{const row=rows[+control.value-1];readout.textContent=row[0];prompt.textContent=row[1];answer.textContent=row[2]}}
 else if(item.visual.kind==='birthday-posts'){const rows=[['Xiaoming','13th June · 每年吃生日面','长面条象征长寿'],['家庭记录','Xiaoming · 每年在村里的大树下拍照','照片记录家人共同度过的时光'],['今年计划','Xiaoming · 14岁生日','种一棵小树，记录共同成长'],['Judy','28th July · 与朋友开生日聚会','妈妈做她喜爱的巧克力蛋糕'],['身高记录','Judy · 父亲每年在门上标身高','年度标记可比较成长'],['回复','给 Judy 的新建议','同一株树逐年测量高度，并用 because 说明意义']];control.oninput=()=>{const row=rows[+control.value-1];readout.textContent=row[0];prompt.textContent=row[1];answer.textContent=row[2]}}
 else if(item.visual.kind==='ordinal-calendar'){const rows=[['11th','第11天 · 7月','on 11th July · eleven→eleventh'],['12th','第12天 · 5月','on 12th May · twelve→twelfth'],['13th','第13天 · 6月','on 13th June · thirteen→thirteenth'],['21st','第21天 · 7月','on 21st July · twenty-first'],['22nd','第22天 · 8月','on 22nd August · twenty-second'],['23rd','第23天 · 4月','on 23rd April · twenty-third'],['1st','第1天 · 10月','on 1st October · first'],['2nd','第2天 · 8月','on 2nd August · second'],['3rd','第3天 · 12月','on 3rd December · third'],['4th','第4天 · 6月','on 4th June · fourth']];control.oninput=()=>{const row=rows[+control.value-1];readout.textContent=row[0];prompt.textContent=row[1];answer.textContent=row[2]}}
 else{const names=['eɪ','biː','siː','diː','iː','ef','dʒiː','eɪtʃ','aɪ','dʒeɪ','keɪ','el','em','en','əʊ','piː','kjuː','ɑː','es','tiː','juː','viː','ˈdʌbəljuː','eks','waɪ','zed'];control.oninput=()=>{const i=+control.value-1,letter=String.fromCharCode(65+i);readout.textContent=`${i+1}/26`;prompt.textContent=`${letter} /${names[i]}/`;answer.textContent=`序号 ${i+1} · 点击语音听名称音`}}
}
function crossMission(){
 const verified=verifiedLesson();if(verified)return verified.cross;
 if(book.id==='math7b'&&unit===0)return{title:'修复天文台平行光轨',copy:'转动光束并读取角度。先用数学判断角关系，再用物理解释光路方向，最后用英语说出 parallel、perpendicular 或 vertical angles。',options:['用角度证据判断光轨关系，并说明方向','只看两条线像不像平行','只记住英文术语'],success:'连接完成：角度证据 → 光路方向 → 英语表达。你使用的是同一个关系，不是三张互不相关的知识卡。'};
 if(book.id==='phy8a'&&unit===0)return{title:'校园运动数据侦测',copy:'读取位置—时间数据，计算速度并判断运动方向，再用英语完成一句数据报告。',options:['先读坐标与单位，再算速度并描述方向','只背速度公式','只翻译 motion 这个单词'],success:'连接完成：坐标图提供数据，物理模型解释运动，英语负责准确报告结果。'};
 if(book.id==='eng7b'&&unit===0)return{title:'动物运动观察报告',copy:'观察动物的身体结构与运动数据，选择恰当形容词，并用完整英语句子报告一次测量结果。',options:['观察结构、记录数据，再用完整句表达','只背 animal 单词','只看动物图片'],success:'连接完成：生物结构解释运动差异，数学记录数据，英语完成真实表达。'};
 return{title:'元来通 · 共同任务',copy:book.chapters[unit].cross.copy,options:['用本课概念解决另一个学科中的真实问题','只看术语卡','跳过条件直接猜答案'],success:'迁移完成：你已经把本课母规则用于另一个学科的真实问题。'};
}
function crossVisual(){
 const mission=crossMission(),source=book.subject,target=mission.subject||book.chapters[unit].cross.subject;
 const labels=mission.labels||(book.subject==='英语'?['观察情境','记录数据','用英语报告']:book.subject==='物理'?['观察现象','处理数据','说明规律']:['读取条件','建立关系','跨学科解释']);
 if(book.id==='eng7a'&&unit===9){const cases=[{min:0,max:10,value:10,label:'酸奶瓶数（目标：150元预算）',reading:'10瓶酸奶：85+30+50=165元，超支15元。',help:'先用150－85－30算酸奶预算，再除以每瓶5元。'},{min:42,max:55,value:42,label:'一年后同一棵树的高度（厘米）',reading:'初始42厘米；一年后42厘米；增长0厘米。',help:'设明年读数49厘米，求明年减今年的高度。'},{min:11,max:23,value:11,label:'第二位同学的生日（日，7月）',reading:'11th→11th→23rd；间隔0天、12天。',help:'请让第二位同学的生日排在11日和23日之间，且与第一位间隔10天。'}],c=cases[section];return `<div class="cross-workbench"><div class="cross-route"><span>${source}</span><b>→</b><span>${target}</span><b>→</b><span>共同任务</span></div><h3>${mission.title}</h3><p>${mission.copy}</p><div class="cross-steps">${labels.map((x,i)=>`<button data-cross-step="${i}"><i>${i+1}</i><span>${x}</span></button>`).join('')}</div><div class="cross-simulator"><label>${c.label} <input id="crossControl" type="range" min="${c.min}" max="${c.max}" value="${c.value}"></label><output id="crossReading">${c.reading}</output><div class="cross-meter"><i></i></div></div><p id="crossResult">${c.help} 调整数值后按顺序完成三步。</p></div>`}
 return `<div class="cross-workbench"><div class="cross-route"><span>${source}</span><b>→</b><span>${target}</span><b>→</b><span>共同任务</span></div><h3>${mission.title}</h3><p>${mission.copy}</p><div class="cross-steps">${labels.map((x,i)=>`<button data-cross-step="${i}"><i>${i+1}</i><span>${x}</span></button>`).join('')}</div><div class="cross-simulator"><label>改变条件 <input id="crossControl" type="range" min="0" max="100" value="35"></label><output id="crossReading">观测值 35</output><div class="cross-meter"><i></i></div></div><p id="crossResult">先改变条件，再依次完成三个步骤。</p></div>`;
}
function activateCrossVisual(){
 $('visualTitle').textContent='跨学科共同任务 · '+book.chapters[unit].sections[section];
 $('visualBody').innerHTML=crossVisual();
 const control=$('crossControl'),reading=$('crossReading'),meter=document.querySelector('.cross-meter i'),result=$('crossResult');
 if(book.id==='eng7a'&&unit===9){const currentSection=section,targets=[7,49,21],target=targets[currentSection],readings=[v=>`${v}瓶酸奶：85+6×5+5×${v}=${115+5*v}元；与150元预算相差${Math.abs(35-5*v)}元。`,v=>`同一棵树：今年42厘米，明年${v}厘米，增长${v-42}厘米。`,v=>`7月11th→${v}${v===21?'st':v===22?'nd':v===23?'rd':'th'}→23rd；两段间隔${v-11}天、${23-v}天。`];const update=()=>{const v=+control.value;reading.textContent=readings[currentSection](v);meter.style.width=(100*(v-(+control.min))/(+control.max-(+control.min)))+'%';if(result.textContent.startsWith('任务完成')&&v!==target)result.textContent='条件已改变，请重新核对计算结果。'};control.oninput=update;document.querySelectorAll('[data-cross-step]').forEach((button,i)=>button.onclick=()=>{if(i>0&&!document.querySelector(`[data-cross-step="${i-1}"]`).classList.contains('done')){result.textContent='请先完成前一步，再检查新的数据。';return}if(i===2&&+control.value!==target){result.textContent=currentSection===0?'还需调整数量，使总额恰好150元。':currentSection===1?'高度差应为7厘米：明年读数是多少？':'前两人的生日间隔需为10天；请继续调整。';return}button.classList.add('done');const done=document.querySelectorAll('[data-cross-step].done').length;result.textContent=done<3?`已完成 ${done}/3：${reading.textContent} 继续完成下一步。`:`任务完成：${reading.textContent} ${crossMission().success.replace(/^完成：/,'')}`});return}
 control.oninput=()=>{reading.textContent=`观测值 ${control.value}`;meter.style.width=control.value+'%'};
 document.querySelectorAll('[data-cross-step]').forEach(button=>button.onclick=()=>{button.classList.add('done');const done=document.querySelectorAll('[data-cross-step].done').length,success=crossMission().success.replace(/^完成：/,'');result.textContent=done<3?`已完成 ${done}/3：继续把两个学科的证据连起来。`:`任务完成：${success}`});
}
function visual(){const title=book.chapters[unit].sections[section];$('visualTitle').textContent=stageNames[stage]+' · '+title;if(verifiedLesson()){$('visualBody').innerHTML=verifiedVisual();activateVerifiedVisual();return}if(deep){$('visualBody').innerHTML=book.subject==='数学'?(unit===0?geometryVisual():extraMathVisual()):book.subject==='物理'?physicsDeepVisual():englishDeepVisual();const control=$('geoControl');if(control)control.oninput=()=>{if(book.id==='math7b'&&unit===0){const angle=Math.round(20+(+control.value)*1.4),line=document.querySelector('.moving-line'),out=$('geoReadout');if(line){line.style.transformOrigin='320px 105px';line.style.transform='rotate('+(angle-50)+'deg)'}if(out)out.textContent=angle+'°';const labels=[...document.querySelectorAll('.geometry-demo svg text')].filter(x=>x.textContent.startsWith('∠'));if(labels[0])labels[0].textContent='∠1 '+angle+'°';if(labels[1])labels[1].textContent='∠2 '+(180-angle)+'°';if(labels[2])labels[2].textContent='∠3 '+angle+'°';return}document.querySelector('.moving-line,.distance-line,.translated,.moving-point,.range-line,.shape-fill')?.style.setProperty('transform',`translateX(${(+control.value-50)/3}px) rotate(${(+control.value-50)/10}deg)`);document.querySelector('.experiment-object')?.style.setProperty('transform',`translateX(${(+control.value-50)*2}px)`);document.querySelector('.sound-wave')?.style.setProperty('--progress',`${control.value}%`)};return}if(book.subject==='数学')$('visualBody').innerHTML=`<div class="math-demo"><p>${stage===3?'改变必要条件，原结论还能成立吗？':'观察位置、方向或数量关系怎样变化'}</p><div class="axis"></div><p>${title}</p></div>`;if(book.subject==='物理')$('visualBody').innerHTML=`<div class="physics-demo"><p>${stage===3?'错误实验：同时改变了两个变量':'只改变一个条件，观察现象和读数'}</p><div class="force-object"></div><p>${title}</p></div>`;if(book.subject==='英语')$('visualBody').innerHTML=`<div class="english-demo"><p>Listen · Notice · Speak · Use</p><div class="dialogue"><span>What do you notice?</span><span>I notice the change.</span></div><p>${title}</p></div>`}
function render(){
 const ch=book.chapters[unit],rich=enrichmentPoints(),verified=verifiedLesson();
 $('bookTitle').textContent=`人教版 · ${book.grade}${book.subject}${book.term}`;
 $('chapterTitle').textContent=ch.title+(verified?' · 教材逐课验收版':rich.length?` · ${rich.length}个深化点`:'');
 $('subjectTag').textContent=`${book.subject.toUpperCase()} · ${book.term}`;$('railTitle').textContent=ch.title;
 $('sectionNav').innerHTML=ch.sections.map((x,i)=>`<button class="${i===section?'active':''}" data-section="${i}"><i>${i+1}</i><span>${x}</span></button>`).join('');
 $('sectionCode').textContent=`${ch.title} · 第${section+1}课 · 知识点 ${Math.min(knowledgeIndex+1,Math.max(1,knowledgePoints().length))}/${Math.max(1,knowledgePoints().length)}`;
 $('sectionTitle').textContent=currentKnowledge();
 $('sectionGoal').textContent=verified?.goal||(book.subject==='英语'?'在真实情境中完成听、说、读、写、语音和语法学习。':book.subject==='物理'?'从现象、实验和证据出发建立物理规律。':'通过动态观察、推理与迁移真正理解数学概念。');
 renderKnowledgeMap();$('stages').innerHTML=stageNames.map((x,i)=>`<span class="${i===stage?'active':''}">${i+1} ${x}</span>`).join('');
 let [title,copy]=lessonText(ch,section)[stage];const mission=crossMission();if(stage===6){title=mission.title;copy=mission.copy}
 $('stageLabel').textContent=stage===6?'橙色支线 · 可选跨学科':'教材主线 · AI授课';$('lessonTitle').textContent=title;$('lessonCopy').textContent=copy;$('rule').textContent=verified?copy:stage===3?'规则是否成立取决于条件是否完整；反例用于看清边界。':copy;
 $('crossSubject').textContent='✦ 跨学科知识传送门 · '+(verified?.cross.subject||ch.cross.subject);$('crossTitle').textContent=verified?.cross.title||ch.cross.title;$('crossCopy').textContent=verified?.cross.copy||ch.cross.copy;
 const verifiedStage=verified?.stages[stage],spec=window.StudyMateKnowledgeEngine?.get(book.subject,currentKnowledge()),variant=!verified&&stage===7?window.StudyMateMasteryEngine?.variant(book.subject,currentKnowledge()):null;
 const choices=stage===6?mission.options:verifiedStage?.options||variant?.options||((stage===2||stage===4)&&spec?spec.options:[]);
 $('actions').innerHTML=choices.map((x,i)=>`<button data-choice="${i}">${x}${stage===4?' →':''}</button>`).join('');$('feedback').hidden=true;$('feedback').textContent='';
 $('tutorLevel').textContent=`学习助手 · ${tutorLevel} ${['独立完成','微提示','关键提示','引导教学','完整讲解'][tutorLevel]}`;$('tutorHelp').textContent=tutorLevel<4?'需要提示':'查看完整讲解';
 $('next').textContent=stage<7?'继续下一步 →':knowledgeIndex<knowledgePoints().length-1?'进入下一知识点 →':section<ch.sections.length-1?'进入下一课 →':'返回全学科目录 →';visual();if(stage===6)activateCrossVisual();
}
$('tutorHelp').onclick=()=>{const verified=verifiedLesson(),spec=window.StudyMateKnowledgeEngine?.get(book.subject,currentKnowledge());if(!verified&&!spec)return;tutorLevel=window.StudyMateTutor.nextLevel(tutorLevel);let msg;if(verified){const current=verified.stages[stage],levels=[null,`先关注：${current.copy.split(/[。！？]/)[0]}。`,current.wrong||`把情境中的人物、条件和数量逐一对应，再尝试回答。`,`回到这一阶段的说明：${current.copy}`,current.correct||`${current.copy} 请解释每一步为什么成立。`];msg=levels[tutorLevel];if(stage===6&&tutorLevel>=2)msg=`任务线索：${verified.cross.copy} 请操作中央区的条件并依次完成步骤。`}else msg=window.StudyMateTutor.help(spec,tutorLevel);$('feedback').textContent=msg;$('feedback').hidden=false;$('tutorLevel').textContent=`学习助手 · ${tutorLevel} ${['独立完成','微提示','关键提示','引导教学','完整讲解'][tutorLevel]}`;$('tutorHelp').textContent=tutorLevel<4?'需要提示':'查看完整讲解';window.StudyMateLearningOrchestrator?.hint(learningContext({level:tutorLevel}))};
$('sectionNav').onclick=e=>{const b=e.target.closest('button');if(!b)return;section=+b.dataset.section;knowledgeIndex=0;stage=0;tutorLevel=0;render()};$('next').onclick=()=>{const ch=book.chapters[unit],kp=knowledgePoints();if(stage<7){stage++;tutorLevel=0;render();return}if(knowledgeIndex<kp.length-1){knowledgeIndex++;stage=0;tutorLevel=0;render();return}if(section<ch.sections.length-1){section++;knowledgeIndex=0;stage=0;tutorLevel=0;render();return}location.href='./subjects.html'};$('crossBtn').onclick=()=>{stage=6;tutorLevel=0;render();document.querySelector('.lesson').scrollIntoView({behavior:'smooth'})};$('actions').onclick=e=>{const b=e.target.closest('button');if(!b)return;const buttons=[...$('actions').querySelectorAll('button')];buttons.forEach(x=>x.classList.remove('correct','wrong'));const choice=+b.dataset.choice,spec=window.StudyMateKnowledgeEngine?.get(book.subject,currentKnowledge()),variant=stage===7?window.StudyMateMasteryEngine?.variant(book.subject,currentKnowledge()):null;if(variant){const ctx=learningContext(),flow=window.StudyMateLearningOrchestrator?.transfer(ctx,choice),ev=flow?.evaluation||window.StudyMateMasteryEngine.evaluate(ctx,choice);b.classList.add(ev.ok?'correct':'wrong');$('feedback').textContent=ev.ok?`迁移验证通过。${ev.explain}`:`还没有真正迁移。建议先修复前置知识：${ev.prerequisite||flow?.diagnosis?.prerequisite||'当前概念基础'}。`;$('feedback').hidden=false;return}if((stage===2||stage===4)&&spec){const ok=choice===spec.answer;b.classList.add(ok?'correct':'wrong');$('feedback').textContent=ok?`正确。${spec.explain}`:`先不要换成猜答案。检查：${spec.error}。`;window.StudyMateLearningOrchestrator?.attempt(learningContext({correct:ok,error:ok?'':spec.error,helpLevel:tutorLevel,mode:'practice',stage:evidenceStage()}));$('feedback').hidden=false;return}else{const ok=choice===0;b.classList.add(ok?'correct':'wrong');$('feedback').textContent=ok?mission.success:choice===1?'这还只是术语记忆，没有完成共同任务。请回到真实情境使用本课规则。':'条件不能跳过；先完成观察和数据，再作判断。'}$('feedback').hidden=false};render();
